name: Check for new version and push tag
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  check-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Get Stable Mono Version
        id: mono_version
        run: |
          NEW_VER=$(curl -s http://download.mono-project.com/repo/ubuntu/dists/bionic/main/binary-amd64/Packages | grep 'Package: mono-devel' -A 2 | tail -1 | cut -d' ' -f2 | cut -d- -f1)
          if [[ -n "$(git tag -l v${NEW_VER}) ]]
          then
            echo ::set-output name=version::$NEW_VER
          else
            echo ::set-output name=version::""
          fi
      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.3
        if: steps.mono_version.outputs.version != ''
        with:
          tag_name: ${{ steps.mono_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
